spring:
  application:
    name: gateway-service

  zipkin:
    base-url: http://localhost:9411

  sleuth:
    sampler:
      probability: 1.0
    enabled: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: notebook-service
          uri: lb://notebook-service
          predicates:
            - Path=/**
      globalFilters:
        - name: Sleuth
          args:
           CUSTOMIZABLE_ROUTE_REGEX: /**



server:
  port: 8008

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    org.springframework.cloud.sleuth: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone:  ${DISCOVERY_URL:http://eureka-server:8761}/eureka/
  instance:
    prefer-ip-address: true